# Configuração OTIMIZADA do modelo baseada no EDA
# config/model_config_bottleneck2.yaml - Reduzindo bottleneck para forçar mais erro em anomalias

data:
  path: "data/processed/flows.csv"
  normal_label: 0
  attack_label: 1

features_used: ['bytes', 'pkts', 'iat_mean']

imputation:
  strategy: 'median'

transformers:
  boxcox: ['bytes']
  yeo_johnson: ['pkts', 'iat_mean']

scaler: StandardScaler

architecture:
  multipliers: [4, 2]       # 4×D e 2×D
  bottleneck: 2             # D=2 para forçar mais erro em anomalias
  dropout: [0.4, 0.3, 0.3, 0.4]  # Aumentado dropout para regularização

model:
  optimizer:
    name: "adam"
    learning_rate: 0.001
    beta_1: 0.9
    beta_2: 0.999
  loss: "mse"
  metrics: ["mae"]

training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 200
  validation_split: 0.25
  random_state: 42
  
  early_stopping:
    monitor: 'val_loss'
    patience: 20
    min_delta: 1e-5
    restore_best_weights: true
  
  reduce_lr:
    factor: 0.5
    patience: 10
    min_lr: 1e-6
  
  model_checkpoint:
    save_best_only: true
    save_weights_only: false

threshold:
  percentile: 97
  sigma_multiplier: 2

preprocessing:
  apply_transformations: true
  remove_outliers: true
  outlier_threshold: 3.5
  validation_split: 0.25

output:
  model_dir: "model_v2"
  figures_dir: "model_v2/figures"
  reports_dir: "reports"

reproducibility:
  numpy_seed: 42
  tensorflow_seed: 42
  python_seed: 42

# Flags de execução
flags:
  verbose: true
  save_plots: true
  debug_mode: false